[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["lib/aave-v3-core = aave-v3-core/src", "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
