[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [ "lib/aave-v3-core = aave-v3-core/src", "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@morpho-blue=lib/morpho-blue/src/",
    "@chainlink=lib/chainlink/contracts/src/v0.8"
]
# See more config option